name: ci

permissions:
  contents: read

on: { push: { branches: [main] }, pull_request: {} }

jobs:
  ci:
    uses: JakobMelchard/.github/.github/workflows/node.yml@main
    with:
      check-cmd: npm run check && npm run format:check
      test-cmd: npm test

  hooks:
    uses: JakobMelchard/.github/.github/workflows/hooks.yml@main
    with:
      # need node_modules; the node job runs eslint and prettier --check
      skip: eslint,prettier
